### PR TITLE
ci: Switch to self-hosted runner

### PR DESCRIPTION
**Pull request by srid**
Proudly hosted by @juspay !

Infra PR https://github.com/juspay/nixos-buffet/pull/13

Much simplifies our workflow:

image

And we get to use the builtin Nix `system` names directly in the workflow:

image

### CODE REVIEW

**Comment by srid** [comment]
@shivaraj-bh Getting a bunch of this in CI (our mac studio):

image

**Comment by srid** [comment]
Still running over 1.5 hours ... currently at `apache-kafka-test`

**Comment by shivaraj-bh** [comment]
> Still running over 1.5 hours ... currently at `apache-kafka-test`
> 
> https://github.com/juspay/services-flake/actions/runs/9507348769/job/26206611624
> 
> EDIT: I'm cancelling and restarting it.



> Still running over 1.5 hours ... currently at `apache-kafka-test`
> 
> https://github.com/juspay/services-flake/actions/runs/9507348769/job/26206611624
> 
> EDIT: I'm cancelling and restarting it.

I believe we might need `wait_for_open_port(<port_num>)`, like in nixos modules: https://github.com/NixOS/nixpkgs/blob/3b3f81db169561308698b5dc0d92a03a802f4002/nixos/tests/open-webui.nix#L29C5-L29C44

**Comment by srid** [comment]
Added a Linux runner, but mysql-test failed:

https://github.com/juspay/services-flake/actions/runs/9520309446/job/26245492894

```
mysql-test> [test       ] ERROR 1045 (28000): Access denied for user 'nixbld'@'localhost' (using password: NO)
```

**Comment by srid** [comment]
> I believe we might need `wait_for_open_port(<port_num>)`, like in nixos modules: https://github.com/NixOS/nixpkgs/blob/3b3f81db169561308698b5dc0d92a03a802f4002/nixos/tests/open-webui.nix#L29C5-L29C44

The darwin build worked now. So looks to be a transient issue 🤷🏿

**Comment by srid** [comment]
All passes, except the llm example fails to build on rosetta:

```
       error: Package ‘python3.11-jaxlib-0.4.28’ in /nix/store/63lvc59rjz075kb1f11xww2x2xqpw1pn-source/pkgs/development/python-modules/jaxlib/bin.nix:228 is marked as broken, refusing to evaluate.
```

Note that the CI for `main` branch no longer builds on Intel mac, as `macos-latest` is now an alias for `macos-14`

image

I'll comment out rosetta and file a new issue for it.

**Comment by srid** [comment]
Need to address github rate limits. That's the only thing to do before merging this PR.

**Pull request merged**
