### PR TITLE
[Docs] Home page and getting started

### PR DESCRIPTION
**Pull request by shivaraj-bh**

### CODE REVIEW

**Comment by srid** [comment]
Looks good,

image

But looks like you forgot to commit redis.md,

image

I'll figure out a way to check this in CI (emanote already has broken link check).

**Comment by srid** [comment]
The CI now fails as expected,

image

**Comment by shivaraj-bh** [comment]
> But looks like you forgot to commit redis.md,

I am not entirely sure what would go in there, so thought of adding it separately, in a different PR.

**Review by srid — APPROVED** [review]
LGTM.

Still waiting to hear from @roberth re: https://github.com/flake-parts/community.flake.parts/pull/5

**Pull request merged**
