### PR TITLE
ci: Add m1 runner to matrix

### PR DESCRIPTION
**Pull request by srid**
Trying out https://github.blog/changelog/2024-01-30-github-actions-introducing-the-new-m1-macos-runner-available-to-open-source/

### CODE REVIEW

**Comment by shivaraj-bh** [comment]
It is weird that `clickhouse` keeps running forever without ever quitting on M1 runner.

**Comment by srid** [comment]
FWIW, the m1 runner is actually faster when building,

https://github.com/srid/haskell-template/pull/124

**Comment by shivaraj-bh** [comment]
Resolves https://github.com/juspay/services-flake/issues/14

**Comment by shivaraj-bh** [comment]
this can be merged now

**Pull request merged**
