### PR TITLE
ci: add `update-flake-lock` cron jobs for `example-{simple, share-services}` and `test`

### LINKED ISSUE #167: ci: Update example sub-flakes on regular basis
Much like we do for https://github.com/srid/haskell-flake

This makes sure that our module and example works with latest nixpkgs, process-compose, etc.

### PR DESCRIPTION
**Pull request by shivaraj-bh**
resolves #167

### CODE REVIEW

**Comment by shivaraj-bh** [comment]
Ideally it would be preferable to have all these flakes follow the same input, like [in haskell-flake](https://github.com/srid/haskell-flake/blob/e43bc631b413078ffe7b772850005596f7295050/flake.nix#L19-L24), but that will break a couple of just commands that depends on test flake.

**Review by srid — COMMENTED** [review]
Sorry, let this slip by. But LGTM.

The N CI actions for N examples is not scaleable long-term, so we need https://github.com/DeterminateSystems/update-flake-lock/issues/82

**Review by srid — COMMENTED** [review]
Sorry, let this slip by. But LGTM.

The N CI actions for N examples is not scaleable long-term, so we need https://github.com/DeterminateSystems/update-flake-lock/issues/82

**Comment by shivaraj-bh** [comment]
I tried out hci-effects: https://github.com/shivaraj-bh/services-flake/pull/4. It works great, supports multi-flake lock update and also auto-merges the PR.

And I can configure it in the `dev` flake: https://github.com/shivaraj-bh/services-flake/commit/a9a76bae7c9622ff99e5f1f5b1c52ce50a2a79d1

**Comment by srid** [comment]
> I tried out hci-effects: [shivaraj-bh#4](https://github.com/shivaraj-bh/services-flake/pull/4). It works great, supports multi-flake lock update and also auto-merges the PR.
> 
> And I can configure it in the `dev` flake: [shivaraj-bh@a9a76ba](https://github.com/shivaraj-bh/services-flake/commit/a9a76bae7c9622ff99e5f1f5b1c52ce50a2a79d1)

Would be nice if we can decouple that from HCI, so as to be able to reuse it in Github Actions. I haven't looked at it in detail though.

But to use HCI (vs self-hosted Github runners) for juspay projects is something that takes a larger consideration (if you remember, we did discuss it internally last year a bit).

**Pull request merged**
